// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#ifndef _SQUARELINE_PROJECT_2_UI_H
#define _SQUARELINE_PROJECT_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_uiScreenMain.h"
#include "ui_uiScreenLog.h"
#include "ui_uiScreenSystem.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_fontHistorico);
LV_FONT_DECLARE(ui_font_FontSDconfig);
LV_FONT_DECLARE(ui_font_fontSub);
LV_FONT_DECLARE(ui_font_fontTEMP);
LV_FONT_DECLARE(ui_font_fonttempgrande);
LV_FONT_DECLARE(ui_font_FonttextAviso);
LV_FONT_DECLARE(ui_font_fontumid);
LV_FONT_DECLARE(ui_font_fontWifi);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
