// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#ifndef _UI_COMP_UI_TEMP_LABEL_H
#define _UI_COMP_UI_TEMP_LABEL_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ui_temp_label
#define UI_COMP_UI_TEMP_LABEL_UI_TEMP_LABEL 0
#define _UI_COMP_UI_TEMP_LABEL_NUM 1
lv_obj_t * ui_ui_temp_label_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
