// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#include "ui.h"

// COMPONENT ui_temp_label

lv_obj_t * ui_ui_temp_label_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ui_temp_label;
    cui_ui_temp_label = lv_label_create(comp_parent);
    lv_obj_set_width(cui_ui_temp_label, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(cui_ui_temp_label, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(cui_ui_temp_label, -1);
    lv_obj_set_y(cui_ui_temp_label, -1);
    lv_obj_set_align(cui_ui_temp_label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_ui_temp_label, "foto do pin");
    lv_obj_set_style_text_color(cui_ui_temp_label, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ui_temp_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(cui_ui_temp_label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_ui_temp_label, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_UI_TEMP_LABEL_NUM);
    children[UI_COMP_UI_TEMP_LABEL_UI_TEMP_LABEL] = cui_ui_temp_label;
    lv_obj_add_event_cb(cui_ui_temp_label, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ui_temp_label, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ui_temp_label_create_hook(cui_ui_temp_label);
    return cui_ui_temp_label;
}

