// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#include "ui.h"

void ui_comp_ui_temp_label_create_hook(lv_obj_t * comp)
{
}
