// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void mudar_brilho_action(lv_event_t * e);
void ativar_setup_wifi(lv_event_t * e);
void Atualizar_Popup_Infos(lv_event_t * e);
void reset_logs_action(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
