// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#ifndef UI_UISCREENMAIN_H
#define UI_UISCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenMain
extern void ui_uiScreenMain_screen_init(void);
extern void ui_uiScreenMain_screen_destroy(void);
extern void ui_event_uiScreenMain(lv_event_t * e);
extern lv_obj_t * ui_uiScreenMain;
extern lv_obj_t * ui_uiarcTemp;
extern lv_obj_t * ui_uilabelTemp;
extern lv_obj_t * ui_uilabelUmid;
extern lv_obj_t * ui_uilabelTime;
extern lv_obj_t * ui_uiiconSD;
extern lv_obj_t * ui_uiiconWiFi;
// CUSTOM VARIABLES
extern lv_obj_t * uic_uiScreenMain;
extern lv_obj_t * uic_uiarcTemp;
extern lv_obj_t * uic_uilabelTemp;
extern lv_obj_t * uic_uilabelUmid;
extern lv_obj_t * uic_uilabelTime;
extern lv_obj_t * uic_uiiconSD;
extern lv_obj_t * uic_uiiconWiFi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

