// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#ifndef UI_UISCREENLOG_H
#define UI_UISCREENLOG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenLog
extern void ui_uiScreenLog_screen_init(void);
extern void ui_uiScreenLog_screen_destroy(void);
extern void ui_event_uiScreenLog(lv_event_t * e);
extern lv_obj_t * ui_uiScreenLog;
extern lv_obj_t * ui_uichartTemp;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_uiScreenLog;
extern lv_obj_t * uic_uichartTemp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

