// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#include "ui.h"

lv_obj_t * uic_uiPanelQRWiFi;
lv_obj_t * uic_uibtnConfirmarReset;
lv_obj_t * uic_uibtnCancelarReset;
lv_obj_t * uic_uibtnFecharInfos;
lv_obj_t * uic_uiLabelVersion;
lv_obj_t * uic_uiLabelSDStatus;
lv_obj_t * uic_uiLabelIP;
lv_obj_t * uic_uiLabelSSID;
lv_obj_t * uic_uiPanelInfos;
lv_obj_t * uic_uibtnConfig;
lv_obj_t * uic_uisliderBrightness;
lv_obj_t * uic_uilabelSettingsTitle;
lv_obj_t * uic_uiScreenSystem;
lv_obj_t * ui_uiScreenSystem = NULL;
lv_obj_t * ui_uilabelSettingsTitle = NULL;
lv_obj_t * ui_uisliderBrightness = NULL;
lv_obj_t * ui_uibtnReset = NULL;
lv_obj_t * ui_uibtnTelegram = NULL;
lv_obj_t * ui_uibtnWifi = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_uibtnConfig = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_uiPanelInfos = NULL;
lv_obj_t * ui_uiLabelSSID = NULL;
lv_obj_t * ui_uiLabelIP = NULL;
lv_obj_t * ui_uiLabelSDStatus = NULL;
lv_obj_t * ui_uiLabelVersion = NULL;
lv_obj_t * ui_uibtnFecharInfos = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_uiPanelConfirmReset = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_uibtnCancelarReset = NULL;
lv_obj_t * ui_uibtnConfirmarReset = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_uiPanelTelegram = NULL;
lv_obj_t * ui_uiQRArea = NULL;
lv_obj_t * ui_uilabelSettingsTitle2 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_uiPanelSetupWiFi = NULL;
lv_obj_t * ui_uiPanelQRWiFi = NULL;
lv_obj_t * ui_uilabelSettingsTitle1 = NULL;
lv_obj_t * ui_Label16 = NULL;
// event funtions
void ui_event_uiScreenSystem(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_uiScreenMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_uiScreenMain_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_uiScreenLog, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_uiScreenLog_screen_init);
    }
}

void ui_event_uisliderBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mudar_brilho_action(e);
    }
}

void ui_event_uibtnReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_uiPanelConfirmReset, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_opacity_set(ui_uibtnReset, 150);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_opacity_set(ui_uibtnReset, 255);
    }
}

void ui_event_uibtnTelegram(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPanelTelegram, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_uibtnWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPanelSetupWiFi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ativar_setup_wifi(e);
    }
}

void ui_event_uibtnConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Atualizar_Popup_Infos(e);
    }
}

void ui_event_uibtnFecharInfos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPanelInfos, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_uibtnCancelarReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPanelConfirmReset, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_uibtnConfirmarReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        reset_logs_action(e);
    }
}

void ui_event_uiPanelTelegram(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPanelTelegram, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_uiPanelSetupWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPanelSetupWiFi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_uiScreenSystem_screen_init(void)
{
    ui_uiScreenSystem = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_uiScreenSystem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiScreenSystem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiScreenSystem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uilabelSettingsTitle = lv_label_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uilabelSettingsTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelSettingsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uilabelSettingsTitle, 0);
    lv_obj_set_y(ui_uilabelSettingsTitle, -165);
    lv_obj_set_align(ui_uilabelSettingsTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelSettingsTitle, "CONFIGURAÇÕES");
    lv_obj_set_style_text_color(ui_uilabelSettingsTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uilabelSettingsTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uilabelSettingsTitle, &ui_font_fontHistorico, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uisliderBrightness = lv_slider_create(ui_uiScreenSystem);
    lv_slider_set_range(ui_uisliderBrightness, 1, 100);
    lv_slider_set_value(ui_uisliderBrightness, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_uisliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_uisliderBrightness, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_uisliderBrightness, 260);
    lv_obj_set_height(ui_uisliderBrightness, 30);
    lv_obj_set_x(ui_uisliderBrightness, 0);
    lv_obj_set_y(ui_uisliderBrightness, 165);
    lv_obj_set_align(ui_uisliderBrightness, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uisliderBrightness, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uisliderBrightness, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uisliderBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_uisliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uisliderBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_uisliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uisliderBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uisliderBrightness, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uisliderBrightness, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uisliderBrightness, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uisliderBrightness, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_uibtnReset = lv_btn_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uibtnReset, 170);
    lv_obj_set_height(ui_uibtnReset, 50);
    lv_obj_set_x(ui_uibtnReset, -100);
    lv_obj_set_y(ui_uibtnReset, -75);
    lv_obj_set_align(ui_uibtnReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uibtnReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uibtnReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uibtnReset, lv_color_hex(0x6B6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtnReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uibtnReset, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uibtnReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uibtnReset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtnTelegram = lv_btn_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uibtnTelegram, 170);
    lv_obj_set_height(ui_uibtnTelegram, 50);
    lv_obj_set_x(ui_uibtnTelegram, 100);
    lv_obj_set_y(ui_uibtnTelegram, 55);
    lv_obj_set_align(ui_uibtnTelegram, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uibtnTelegram, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uibtnTelegram, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uibtnTelegram, lv_color_hex(0x6B6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtnTelegram, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uibtnTelegram, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uibtnTelegram, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uibtnTelegram, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtnWifi = lv_btn_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uibtnWifi, 170);
    lv_obj_set_height(ui_uibtnWifi, 50);
    lv_obj_set_x(ui_uibtnWifi, 100);
    lv_obj_set_y(ui_uibtnWifi, -75);
    lv_obj_set_align(ui_uibtnWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uibtnWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uibtnWifi, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uibtnWifi, lv_color_hex(0x6B6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtnWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uibtnWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uibtnWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uibtnWifi, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -120);
    lv_obj_set_y(ui_Label10, -75);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "LIMPAR SD");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 100);
    lv_obj_set_y(ui_Label12, 55);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "TELEGRAM");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -65);
    lv_obj_set_y(ui_Label9, 120);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "LUMINOSIDADE");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -40);
    lv_obj_set_y(ui_Label2, -75);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_FontSDconfig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 75);
    lv_obj_set_y(ui_Label13, -75);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "WIFI");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 140);
    lv_obj_set_y(ui_Label14, -75);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_FontSDconfig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtnConfig = lv_btn_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uibtnConfig, 170);
    lv_obj_set_height(ui_uibtnConfig, 50);
    lv_obj_set_x(ui_uibtnConfig, -100);
    lv_obj_set_y(ui_uibtnConfig, 55);
    lv_obj_set_align(ui_uibtnConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uibtnConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uibtnConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uibtnConfig, lv_color_hex(0x6B6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtnConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uibtnConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uibtnConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uibtnConfig, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -100);
    lv_obj_set_y(ui_Label3, 55);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "INFOS ");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiPanelInfos = lv_obj_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uiPanelInfos, 485);
    lv_obj_set_height(ui_uiPanelInfos, 485);
    lv_obj_set_align(ui_uiPanelInfos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiPanelInfos, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_uiPanelInfos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiPanelInfos, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiPanelInfos, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPanelInfos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiPanelInfos, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiPanelInfos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPanelInfos, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelSSID = lv_label_create(ui_uiPanelInfos);
    lv_obj_set_width(ui_uiLabelSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelSSID, -88);
    lv_obj_set_y(ui_uiLabelSSID, 80);
    lv_obj_set_align(ui_uiLabelSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelSSID, "Rede: ---");
    lv_obj_set_style_text_color(ui_uiLabelSSID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelSSID, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelIP = lv_label_create(ui_uiPanelInfos);
    lv_obj_set_width(ui_uiLabelIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelIP, -100);
    lv_obj_set_y(ui_uiLabelIP, -40);
    lv_obj_set_align(ui_uiLabelIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelIP, "IP: ---");
    lv_obj_set_style_text_color(ui_uiLabelIP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelIP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelIP, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelSDStatus = lv_label_create(ui_uiPanelInfos);
    lv_obj_set_width(ui_uiLabelSDStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelSDStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelSDStatus, -100);
    lv_obj_set_y(ui_uiLabelSDStatus, 20);
    lv_obj_set_align(ui_uiLabelSDStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelSDStatus, "SD: ---");
    lv_obj_set_style_text_color(ui_uiLabelSDStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelSDStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelSDStatus, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelVersion = lv_label_create(ui_uiPanelInfos);
    lv_obj_set_width(ui_uiLabelVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelVersion, 0);
    lv_obj_set_y(ui_uiLabelVersion, -115);
    lv_obj_set_align(ui_uiLabelVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelVersion, "Versão: ---");
    lv_obj_set_style_text_color(ui_uiLabelVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelVersion, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtnFecharInfos = lv_btn_create(ui_uiPanelInfos);
    lv_obj_set_width(ui_uibtnFecharInfos, 150);
    lv_obj_set_height(ui_uibtnFecharInfos, 50);
    lv_obj_set_x(ui_uibtnFecharInfos, 0);
    lv_obj_set_y(ui_uibtnFecharInfos, 180);
    lv_obj_set_align(ui_uibtnFecharInfos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uibtnFecharInfos, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uibtnFecharInfos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uibtnFecharInfos, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtnFecharInfos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uibtnFecharInfos, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uibtnFecharInfos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uibtnFecharInfos, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_uiPanelInfos);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 180);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "VOLTAR");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_uiPanelInfos);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -165);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SISTEMA");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_fontHistorico, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiPanelConfirmReset = lv_obj_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uiPanelConfirmReset, 490);
    lv_obj_set_height(ui_uiPanelConfirmReset, 490);
    lv_obj_set_align(ui_uiPanelConfirmReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiPanelConfirmReset, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_uiPanelConfirmReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiPanelConfirmReset, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiPanelConfirmReset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPanelConfirmReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiPanelConfirmReset, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiPanelConfirmReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPanelConfirmReset, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_uiPanelConfirmReset);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -165);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "ATENÇÃO!");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xF4CB02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_fontHistorico, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_uiPanelConfirmReset);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -15);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Isso vai apagar todos os dados\nde temperatura e umidade. \nTem certeza?");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_FonttextAviso, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtnCancelarReset = lv_btn_create(ui_uiPanelConfirmReset);
    lv_obj_set_width(ui_uibtnCancelarReset, 150);
    lv_obj_set_height(ui_uibtnCancelarReset, 50);
    lv_obj_set_x(ui_uibtnCancelarReset, -100);
    lv_obj_set_y(ui_uibtnCancelarReset, 125);
    lv_obj_set_align(ui_uibtnCancelarReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uibtnCancelarReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uibtnCancelarReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uibtnCancelarReset, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtnCancelarReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uibtnCancelarReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uibtnCancelarReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uibtnCancelarReset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtnConfirmarReset = lv_btn_create(ui_uiPanelConfirmReset);
    lv_obj_set_width(ui_uibtnConfirmarReset, 150);
    lv_obj_set_height(ui_uibtnConfirmarReset, 50);
    lv_obj_set_x(ui_uibtnConfirmarReset, 100);
    lv_obj_set_y(ui_uibtnConfirmarReset, 125);
    lv_obj_set_align(ui_uibtnConfirmarReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uibtnConfirmarReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uibtnConfirmarReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uibtnConfirmarReset, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtnConfirmarReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uibtnConfirmarReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uibtnConfirmarReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uibtnConfirmarReset, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_uiPanelConfirmReset);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -100);
    lv_obj_set_y(ui_Label1, 125);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "VOLTAR");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_uiPanelConfirmReset);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 100);
    lv_obj_set_y(ui_Label4, 125);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "CONFIRMAR");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiPanelTelegram = lv_obj_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uiPanelTelegram, 480);
    lv_obj_set_height(ui_uiPanelTelegram, 480);
    lv_obj_set_align(ui_uiPanelTelegram, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiPanelTelegram, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_uiPanelTelegram, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiPanelTelegram, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiPanelTelegram, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPanelTelegram, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiPanelTelegram, lv_color_hex(0x0088CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiPanelTelegram, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPanelTelegram, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiQRArea = lv_obj_create(ui_uiPanelTelegram);
    lv_obj_set_width(ui_uiQRArea, 280);
    lv_obj_set_height(ui_uiQRArea, 280);
    lv_obj_set_align(ui_uiQRArea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiQRArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiQRArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uilabelSettingsTitle2 = lv_label_create(ui_uiPanelTelegram);
    lv_obj_set_width(ui_uilabelSettingsTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelSettingsTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uilabelSettingsTitle2, 0);
    lv_obj_set_y(ui_uilabelSettingsTitle2, -165);
    lv_obj_set_align(ui_uilabelSettingsTitle2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelSettingsTitle2, "NOTIFICAÇÕES");
    lv_obj_set_style_text_color(ui_uilabelSettingsTitle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uilabelSettingsTitle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uilabelSettingsTitle2, &ui_font_fontHistorico, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_uiPanelTelegram);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 170);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Leia o QR Code para \nconectar o seu Telegram.");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiPanelSetupWiFi = lv_obj_create(ui_uiScreenSystem);
    lv_obj_set_width(ui_uiPanelSetupWiFi, 480);
    lv_obj_set_height(ui_uiPanelSetupWiFi, 480);
    lv_obj_set_align(ui_uiPanelSetupWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiPanelSetupWiFi, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_uiPanelSetupWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiPanelSetupWiFi, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiPanelSetupWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPanelSetupWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiPanelSetupWiFi, lv_color_hex(0x0088CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiPanelSetupWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPanelSetupWiFi, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiPanelQRWiFi = lv_obj_create(ui_uiPanelSetupWiFi);
    lv_obj_set_width(ui_uiPanelQRWiFi, 280);
    lv_obj_set_height(ui_uiPanelQRWiFi, 280);
    lv_obj_set_align(ui_uiPanelQRWiFi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPanelQRWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiPanelQRWiFi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uilabelSettingsTitle1 = lv_label_create(ui_uiPanelSetupWiFi);
    lv_obj_set_width(ui_uilabelSettingsTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelSettingsTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uilabelSettingsTitle1, 0);
    lv_obj_set_y(ui_uilabelSettingsTitle1, -165);
    lv_obj_set_align(ui_uilabelSettingsTitle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelSettingsTitle1, "WIFI");
    lv_obj_set_style_text_color(ui_uilabelSettingsTitle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uilabelSettingsTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uilabelSettingsTitle1, &ui_font_fontHistorico, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_uiPanelSetupWiFi);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, 170);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Leia o QR Code para \nconectar o Wifi.");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_fontSub, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_uisliderBrightness, ui_event_uisliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uibtnReset, ui_event_uibtnReset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uibtnTelegram, ui_event_uibtnTelegram, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uibtnWifi, ui_event_uibtnWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uibtnConfig, ui_event_uibtnConfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uibtnFecharInfos, ui_event_uibtnFecharInfos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uibtnCancelarReset, ui_event_uibtnCancelarReset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uibtnConfirmarReset, ui_event_uibtnConfirmarReset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiPanelTelegram, ui_event_uiPanelTelegram, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiPanelSetupWiFi, ui_event_uiPanelSetupWiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiScreenSystem, ui_event_uiScreenSystem, LV_EVENT_ALL, NULL);
    uic_uiScreenSystem = ui_uiScreenSystem;
    uic_uilabelSettingsTitle = ui_uilabelSettingsTitle;
    uic_uisliderBrightness = ui_uisliderBrightness;
    uic_uibtnConfig = ui_uibtnConfig;
    uic_uiPanelInfos = ui_uiPanelInfos;
    uic_uiLabelSSID = ui_uiLabelSSID;
    uic_uiLabelIP = ui_uiLabelIP;
    uic_uiLabelSDStatus = ui_uiLabelSDStatus;
    uic_uiLabelVersion = ui_uiLabelVersion;
    uic_uibtnFecharInfos = ui_uibtnFecharInfos;
    uic_uibtnCancelarReset = ui_uibtnCancelarReset;
    uic_uibtnConfirmarReset = ui_uibtnConfirmarReset;
    uic_uiPanelQRWiFi = ui_uiPanelQRWiFi;

}

void ui_uiScreenSystem_screen_destroy(void)
{
    if(ui_uiScreenSystem) lv_obj_del(ui_uiScreenSystem);

    // NULL screen variables
    uic_uiScreenSystem = NULL;
    ui_uiScreenSystem = NULL;
    uic_uilabelSettingsTitle = NULL;
    ui_uilabelSettingsTitle = NULL;
    uic_uisliderBrightness = NULL;
    ui_uisliderBrightness = NULL;
    ui_uibtnReset = NULL;
    ui_uibtnTelegram = NULL;
    ui_uibtnWifi = NULL;
    ui_Label10 = NULL;
    ui_Label12 = NULL;
    ui_Label9 = NULL;
    ui_Label2 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    uic_uibtnConfig = NULL;
    ui_uibtnConfig = NULL;
    ui_Label3 = NULL;
    uic_uiPanelInfos = NULL;
    ui_uiPanelInfos = NULL;
    uic_uiLabelSSID = NULL;
    ui_uiLabelSSID = NULL;
    uic_uiLabelIP = NULL;
    ui_uiLabelIP = NULL;
    uic_uiLabelSDStatus = NULL;
    ui_uiLabelSDStatus = NULL;
    uic_uiLabelVersion = NULL;
    ui_uiLabelVersion = NULL;
    uic_uibtnFecharInfos = NULL;
    ui_uibtnFecharInfos = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_uiPanelConfirmReset = NULL;
    ui_Label8 = NULL;
    ui_Label11 = NULL;
    uic_uibtnCancelarReset = NULL;
    ui_uibtnCancelarReset = NULL;
    uic_uibtnConfirmarReset = NULL;
    ui_uibtnConfirmarReset = NULL;
    ui_Label1 = NULL;
    ui_Label4 = NULL;
    ui_uiPanelTelegram = NULL;
    ui_uiQRArea = NULL;
    ui_uilabelSettingsTitle2 = NULL;
    ui_Label15 = NULL;
    ui_uiPanelSetupWiFi = NULL;
    uic_uiPanelQRWiFi = NULL;
    ui_uiPanelQRWiFi = NULL;
    ui_uilabelSettingsTitle1 = NULL;
    ui_Label16 = NULL;

}
