// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#ifndef UI_UISCREENSYSTEM_H
#define UI_UISCREENSYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenSystem
extern void ui_uiScreenSystem_screen_init(void);
extern void ui_uiScreenSystem_screen_destroy(void);
extern void ui_event_uiScreenSystem(lv_event_t * e);
extern lv_obj_t * ui_uiScreenSystem;
extern lv_obj_t * ui_uilabelSettingsTitle;
extern void ui_event_uisliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_uisliderBrightness;
extern void ui_event_uibtnReset(lv_event_t * e);
extern lv_obj_t * ui_uibtnReset;
extern void ui_event_uibtnTelegram(lv_event_t * e);
extern lv_obj_t * ui_uibtnTelegram;
extern void ui_event_uibtnWifi(lv_event_t * e);
extern lv_obj_t * ui_uibtnWifi;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern void ui_event_uibtnConfig(lv_event_t * e);
extern lv_obj_t * ui_uibtnConfig;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_uiPanelInfos;
extern lv_obj_t * ui_uiLabelSSID;
extern lv_obj_t * ui_uiLabelIP;
extern lv_obj_t * ui_uiLabelSDStatus;
extern lv_obj_t * ui_uiLabelVersion;
extern void ui_event_uibtnFecharInfos(lv_event_t * e);
extern lv_obj_t * ui_uibtnFecharInfos;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_uiPanelConfirmReset;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label11;
extern void ui_event_uibtnCancelarReset(lv_event_t * e);
extern lv_obj_t * ui_uibtnCancelarReset;
extern void ui_event_uibtnConfirmarReset(lv_event_t * e);
extern lv_obj_t * ui_uibtnConfirmarReset;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern void ui_event_uiPanelTelegram(lv_event_t * e);
extern lv_obj_t * ui_uiPanelTelegram;
extern lv_obj_t * ui_uiQRArea;
extern lv_obj_t * ui_uilabelSettingsTitle2;
extern lv_obj_t * ui_Label15;
extern void ui_event_uiPanelSetupWiFi(lv_event_t * e);
extern lv_obj_t * ui_uiPanelSetupWiFi;
extern lv_obj_t * ui_uiPanelQRWiFi;
extern lv_obj_t * ui_uilabelSettingsTitle1;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES
extern lv_obj_t * uic_uiScreenSystem;
extern lv_obj_t * uic_uilabelSettingsTitle;
extern lv_obj_t * uic_uisliderBrightness;
extern lv_obj_t * uic_uibtnConfig;
extern lv_obj_t * uic_uiPanelInfos;
extern lv_obj_t * uic_uiLabelSSID;
extern lv_obj_t * uic_uiLabelIP;
extern lv_obj_t * uic_uiLabelSDStatus;
extern lv_obj_t * uic_uiLabelVersion;
extern lv_obj_t * uic_uibtnFecharInfos;
extern lv_obj_t * uic_uibtnCancelarReset;
extern lv_obj_t * uic_uibtnConfirmarReset;
extern lv_obj_t * uic_uiPanelQRWiFi;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

