// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#include "ui.h"

lv_obj_t * uic_uiiconWiFi;
lv_obj_t * uic_uiiconSD;
lv_obj_t * uic_uilabelTime;
lv_obj_t * uic_uilabelUmid;
lv_obj_t * uic_uilabelTemp;
lv_obj_t * uic_uiarcTemp;
lv_obj_t * uic_uiScreenMain;
lv_obj_t * ui_uiScreenMain = NULL;
lv_obj_t * ui_uiarcTemp = NULL;
lv_obj_t * ui_uilabelTemp = NULL;
lv_obj_t * ui_uilabelUmid = NULL;
lv_obj_t * ui_uilabelTime = NULL;
lv_obj_t * ui_uiiconSD = NULL;
lv_obj_t * ui_uiiconWiFi = NULL;
// event funtions
void ui_event_uiScreenMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_uiScreenLog, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_uiScreenLog_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_uiScreenSystem, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_uiScreenSystem_screen_init);
    }
}

// build funtions

void ui_uiScreenMain_screen_init(void)
{
    ui_uiScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_uiScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiScreenMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiarcTemp = lv_arc_create(ui_uiScreenMain);
    lv_obj_set_width(ui_uiarcTemp, 390);
    lv_obj_set_height(ui_uiarcTemp, 390);
    lv_obj_set_align(ui_uiarcTemp, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_uiarcTemp, 200, 350);
    lv_arc_set_value(ui_uiarcTemp, 210);
    lv_arc_set_bg_angles(ui_uiarcTemp, 135, 45);
    lv_obj_set_style_arc_color(ui_uiarcTemp, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_uiarcTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_uiarcTemp, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_uiarcTemp, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_uiarcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_uiarcTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiarcTemp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_uilabelTemp = lv_label_create(ui_uiScreenMain);
    lv_obj_set_width(ui_uilabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uilabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelTemp, "00.0°C");
    lv_obj_set_style_text_color(ui_uilabelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uilabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uilabelTemp, &ui_font_fonttempgrande, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uilabelUmid = lv_label_create(ui_uiScreenMain);
    lv_obj_set_width(ui_uilabelUmid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelUmid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uilabelUmid, 0);
    lv_obj_set_y(ui_uilabelUmid, 90);
    lv_obj_set_align(ui_uilabelUmid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelUmid, "45%");
    lv_obj_set_style_text_color(ui_uilabelUmid, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uilabelUmid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uilabelUmid, &ui_font_fontumid, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uilabelTime = lv_label_create(ui_uiScreenMain);
    lv_obj_set_width(ui_uilabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uilabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uilabelTime, 0);
    lv_obj_set_y(ui_uilabelTime, -90);
    lv_obj_set_align(ui_uilabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uilabelTime, "12:00");
    lv_obj_set_style_text_color(ui_uilabelTime, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uilabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uilabelTime, &ui_font_fontTEMP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiiconSD = lv_label_create(ui_uiScreenMain);
    lv_obj_set_width(ui_uiiconSD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiiconSD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiiconSD, -100);
    lv_obj_set_y(ui_uiiconSD, 160);
    lv_obj_set_align(ui_uiiconSD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiiconSD, "");
    lv_obj_set_style_text_color(ui_uiiconSD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiiconSD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiiconSD, &ui_font_fontWifi, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiiconWiFi = lv_label_create(ui_uiScreenMain);
    lv_obj_set_width(ui_uiiconWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiiconWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiiconWiFi, 100);
    lv_obj_set_y(ui_uiiconWiFi, 160);
    lv_obj_set_align(ui_uiiconWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiiconWiFi, "");
    lv_obj_set_style_text_color(ui_uiiconWiFi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiiconWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiiconWiFi, &ui_font_fontWifi, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_uiScreenMain, ui_event_uiScreenMain, LV_EVENT_ALL, NULL);
    uic_uiScreenMain = ui_uiScreenMain;
    uic_uiarcTemp = ui_uiarcTemp;
    uic_uilabelTemp = ui_uilabelTemp;
    uic_uilabelUmid = ui_uilabelUmid;
    uic_uilabelTime = ui_uilabelTime;
    uic_uiiconSD = ui_uiiconSD;
    uic_uiiconWiFi = ui_uiiconWiFi;

}

void ui_uiScreenMain_screen_destroy(void)
{
    if(ui_uiScreenMain) lv_obj_del(ui_uiScreenMain);

    // NULL screen variables
    uic_uiScreenMain = NULL;
    ui_uiScreenMain = NULL;
    uic_uiarcTemp = NULL;
    ui_uiarcTemp = NULL;
    uic_uilabelTemp = NULL;
    ui_uilabelTemp = NULL;
    uic_uilabelUmid = NULL;
    ui_uilabelUmid = NULL;
    uic_uilabelTime = NULL;
    ui_uilabelTime = NULL;
    uic_uiiconSD = NULL;
    ui_uiiconSD = NULL;
    uic_uiiconWiFi = NULL;
    ui_uiiconWiFi = NULL;

}
