// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#include "ui.h"

lv_obj_t * uic_uichartTemp;
lv_obj_t * uic_uiScreenLog;
lv_obj_t * ui_uiScreenLog = NULL;
lv_obj_t * ui_uichartTemp = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_uiScreenLog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_uiScreenSystem, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_uiScreenSystem_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_uiScreenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_uiScreenMain_screen_init);
    }
}

// build funtions

void ui_uiScreenLog_screen_init(void)
{
    ui_uiScreenLog = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_uiScreenLog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiScreenLog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiScreenLog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uichartTemp = lv_chart_create(ui_uiScreenLog);
    lv_obj_set_width(ui_uichartTemp, 300);
    lv_obj_set_height(ui_uichartTemp, 250);
    lv_obj_set_x(ui_uichartTemp, 0);
    lv_obj_set_y(ui_uichartTemp, 20);
    lv_obj_set_align(ui_uichartTemp, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_uichartTemp, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_uichartTemp, 24);
    lv_chart_set_range(ui_uichartTemp, LV_CHART_AXIS_PRIMARY_Y, -10, 20);
    lv_chart_set_div_line_count(ui_uichartTemp, 3, 2);
    lv_chart_set_axis_tick(ui_uichartTemp, LV_CHART_AXIS_PRIMARY_X, 10, 5, 1, 2, false, 50);
    lv_chart_set_axis_tick(ui_uichartTemp, LV_CHART_AXIS_PRIMARY_Y, 4, 5, 4, 2, true, 50);
    lv_chart_set_axis_tick(ui_uichartTemp, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_obj_set_style_bg_color(ui_uichartTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uichartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uichartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_uichartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_uichartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_uichartTemp, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_uichartTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_uichartTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_uichartTemp, lv_color_hex(0xB0B0B0), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_uichartTemp, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_uichartTemp, lv_color_hex(0xB0B0B0), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uichartTemp, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_uiScreenLog);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -165);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "HISTÓRICO 24H");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_fontHistorico, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_uiScreenLog, ui_event_uiScreenLog, LV_EVENT_ALL, NULL);
    uic_uiScreenLog = ui_uiScreenLog;
    uic_uichartTemp = ui_uichartTemp;

}

void ui_uiScreenLog_screen_destroy(void)
{
    if(ui_uiScreenLog) lv_obj_del(ui_uiScreenLog);

    // NULL screen variables
    uic_uiScreenLog = NULL;
    ui_uiScreenLog = NULL;
    uic_uichartTemp = NULL;
    ui_uichartTemp = NULL;
    ui_Label7 = NULL;

}
